version: '3'
services:
  # Redis session and queue management
  redis:
    container_name: redis
    restart: always
    image: redis:3.2-alpine
    networks:
      - gateway

  # Cerbot
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot:/var/www/html/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot-path /var/www/html/certbot; sleep 12h & wait $${!}; done;'"
    networks:
      - gateway

  app:
    build: .
    restart: always
    image: laravel-alpine
    container_name: app
    tty: true
    environment:
      DOCKER_APP: app
    working_dir: /var/www/html
    networks:
      - gateway
    env_file:
      - .env

networks:
  gateway:
    external: true

