version: '3'
services:
  # Webserver for Reverse proxy
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./docker-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
      - ./certbot:/var/www/html/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - gateway
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-labkes-app"
           awslogs-stream: "prod-nginx"

  # Redis session and queue management
  redis:
    container_name: redis
    restart: always
    image: redis:3.2-alpine
    networks:
      - gateway
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-labkes-app"
           awslogs-stream: "prod-redis"

  # Cerbot
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot:/var/www/html/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot-path /var/www/certbot; sleep 12h & wait $${!}; done;'"
    networks:
      - gateway
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-labkes-app"
           awslogs-stream: "prod-certbot"

  app:
    build: .
    restart: always
    image: laravel-alpine
    container_name: app
    tty: true
    environment:
      DOCKER_APP: app
    working_dir: /var/www/html
    command: "/bin/sh -c 'php artisan optimize'"
    volumes:
      - ./:/var/www/html
    networks:
      - gateway
    env_file:
      - .env
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-labkes-app"
           awslogs-stream: "prod-queue-app"

networks:
  gateway:
    external: true

